# dvc.yaml CORREGIDO

stages:
  # 1. Limpieza, Winsorización y Transformación del Target (make_dataset.py)
  process_data:
    cmd: python src/data/make_dataset.py data/raw/bike_sharing_modified.csv data/processed/bike_sharing_processed.csv
    deps:
      - src/data/make_dataset.py
      - data/raw/bike_sharing_modified.csv 
    outs:
      - data/processed/bike_sharing_processed.csv

  # 2. División de Datos por Tiempo, Ingeniería de Features y Guardado del Preprocesador (build_features.py)
  # NOTA: Esta etapa sigue rastreando el directorio intermedio.
  split_and_preprocess:
    cmd: python src/features/build_features.py data/processed/bike_sharing_processed.csv data/interim models/preprocessor.pkl
    deps:
      - src/features/build_features.py
      - data/processed/bike_sharing_processed.csv
    outs:
      - data/interim/  # Directorio que contiene X_train.csv, y_train.csv, X_test.csv, y_test.csv
      - models/preprocessor.pkl

  # 3. Entrenamiento del Pipeline, Evaluación y Registro en MLflow (train_model.py)
  train_model:
    cmd: python src/models/train_model.py data/interim models/preprocessor.pkl models/final_pipeline.pkl
    deps:
      - src/models/train_model.py
      - data/interim/
      - models/preprocessor.pkl
    outs:
      - models/final_pipeline.pkl

  # 4. Generación de Predicciones con el Pipeline Final (predict_model.py)
  predict:
    cmd: python src/models/predict_model.py models/final_pipeline.pkl data/interim/X_test.csv data/results/predictions_final.csv
    deps:
      - src/models/predict_model.py
      - models/final_pipeline.pkl
      - data/interim/X_test.csv
    outs:
      - data/results/predictions_final.csv

  # 5. Visualización de Resultados (visualize.py)
  visualize:
    cmd: python src/visualization/visualize.py data/results/predictions_final.csv data/interim/y_test.csv reports/figures/predictions_vs_real.png
    deps:
      - src/visualization/visualize.py
      - data/results/predictions_final.csv
      - data/interim/y_test.csv
    outs:
      - reports/figures/predictions_vs_real.png